# Generated by Django 3.2.12 on 2022-08-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='view',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
