# Generated by Django 3.2.12 on 2022-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_img',
            field=models.ImageField(blank=True, default='crew/image/상점기본.png', null=True, upload_to='crew/image'),
        ),
    ]
