# Generated by Django 3.2.11 on 2022-04-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('코미디', '코미디'), ('러브코미디', '러브코미디'), ('느와르', '느와르')], max_length=30),
        ),
    ]
