version: '3.7'
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/test/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static 
      - media-volume:/data/media
      # - media-volume:/data/media
    ports:
      - 80:80 
      - 443:443
  # # 컨테이너 이름으로 소통이 진행되므로, 이름을 container 이름으로 지어주자
  frontend :
    image : fe:2.8
    networks:
     - network

  backend:
    image: be:2.6
    networks:
      - network
    volumes:
      - static-volume:/home/S07P12B209/BE/staticfiles 
      - media-volume:/home/S07P12B209/BE/media 
    secrets :
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
  # db는 배포 환경의 HOST Name과 같게 해야한다. 
  mariadb:
    image: mariadb:10.5
    networks:
      - network 
    volumes:
    # 경로는 docker hub에 명시된 /var/lib/mysql로 설정하자
      - maria-database:/var/lib/mysql 
    # mariadb secret을 만들 때 _FILE이라는 접미사로 설정할 수 있고, secret의 경로를 제공해줘야한다. 
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD 
    environment:
      MYSQL_ROOT_PASSWORD_FILE : /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE : b209
      MYSQL_USER : b209 
      MYSQL_PASSWORD_FILE : /run/secrets/MYSQL_PASSWORD
    ports:
      - 33061:3306

networks:
  network:

volumes:
  static-volume: 
  media-volume:
  maria-database: 
      
secrets:
  DJANGO_SECRET_KEY:
    external: true 

  MYSQL_PASSWORD:
    external: true 

  MYSQL_ROOT_PASSWORD:
    external: true